INCLUDE(ExternalProject)

SET(DUCKDB_NAME "duckdb")
SET(DUCKDB_DIR "extra/${DUCKDB_NAME}")
SET(DUCKDB_SOURCE_DIR "${CMAKE_SOURCE_DIR}/${DUCKDB_DIR}")

# duckdb build tweaks
SET(DUCKDB_CMAKE_VARS "-DCMAKE_CXX_STANDARD=17 -DCMAKE_CXX_STANDARD_REQUIRED=ON -DBUILD_SHELL=0 -DBUILD_PYTHON=0 -DBUILD_UNITTESTS=0")

IF(CMAKE_BUILD_TYPE STREQUAL "Debug")
  SET(DUCKDB_BUILD_TYPE "bundle-library-debug")
  SET(DUCKDB_BUILD_DIR "debug")
ELSE()
  SET(DUCKDB_BUILD_TYPE "bundle-library")
  SET(DUCKDB_BUILD_DIR "release")
ENDIF()

SET(DUCKDB_DIR "extra/duckdb")

MACRO (MYSQL_USE_BONDLED_DUCKDB)
  MESSAGE (STATUS "DUCKDB Make Begin")


  SET(BINARY_DIR "${CMAKE_BINARY_DIR}/${CMAKE_CFG_INTDIR}/${DUCKDB_DIR}/build")
  SET(DUCKDB_INCLUDE_DIR ${DUCKDB_SOURCE_DIR}/src/include)

  ExternalProject_Add(duckdb_proj
    PREFIX ${DUCKDB_DIR}
    SOURCE_DIR ${DUCKDB_SOURCE_DIR}
    BINARY_DIR ${BINARY_DIR}
    STAMP_DIR  ${BINARY_DIR}
    CONFIGURE_COMMAND ""
    BUILD_COMMAND make -C ../ ${DUCKDB_BUILD_TYPE}
    INSTALL_COMMAND ""
  )

  SET(MY_DUCKDB_LIB "${BINARY_DIR}/${DUCKDB_BUILD_DIR}/libduckdb_bundle.a")
  MESSAGE (STATUS "MY_DUCKDB_LIB path: ${MY_DUCKDB_LIB}")
  ADD_LIBRARY(libduckdb STATIC IMPORTED)

  SET_TARGET_PROPERTIES(libduckdb PROPERTIES IMPORTED_LOCATION "${MY_DUCKDB_LIB}")
  ADD_DEPENDENCIES(libduckdb duckdb_proj)
  INCLUDE_DIRECTORIES(BEFORE SYSTEM ${DUCKDB_INCLUDE_DIR})
  MESSAGE (STATUS "DUCKDB Make End")
ENDMACRO()

MACRO (MYSQL_CHECK_DUCKDB)
  MYSQL_USE_BONDLED_DUCKDB()
  SET(DUCKDB_LIBRARY libduckdb)
ENDMACRO()
